camera:
  device_id: "/dev/video1"
  width: 1280
  height: 720
  fps: 30
yolo:
  model_path: "models/yolov8n.onnx"
  confidence_threshold: 0.7
  imgsz: 640
  iou_threshold: 0.5
  send_images: true
gps:
  port: "/dev/ttyUSB1"
  baudrate: 115200
  timeout: 1
  power_delay: 2
  agps_delay: 5
imu:
  i2c_bus: 4
  i2c_addresses: ["0x68", "0x69"]  # Try both addresses due to floating AD0 pin
  sample_rate: 100
  accel_range: 2
  gyro_range: 250
sim:
  port: "/dev/ttyUSB1"
  baudrate: 115200
  ussd_balance_code: "*221#"
  check_interval: 3600
backend:
  url: "https://vehicle-tracking-backend-bwmz.onrender.com"
  endpoint_prefix: "/api"
  detection_endpoint: "/detections"
  sim_data_endpoint: "/sim-data"
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "vehicle_tracker.log"
  offline_file: "offline_data.json"
  interval:
    gps: 1
    imu: 0.1
    camera: 5

api:
  port: 5000
