camera:
  device_id: "/dev/video1"
  width: 640
  height: 360
  fps: 30
yolo:
  model_path: "models/yolov8n.onnx"
  confidence_threshold: 0.5
  imgsz: 416
  iou_threshold: 0.45
  send_images: false
  class_names:
    - Green Light
    - Red Light
    - Speed Limit 10
    - Speed Limit 100
    - Speed Limit 110
    - Speed Limit 120
    - Speed Limit 20
    - Speed Limit 30
    - Speed Limit 40
    - Speed Limit 50
    - Speed Limit 60
    - Speed Limit 70
    - Speed Limit 80
    - Speed Limit 90
    - Stop
  intra_op_num_threads: 8
  draw_boxes: true
gps:
  port: "/dev/ttyUSB1"
  baudrate: 115200
  timeout: 1
  power_delay: 2
  agps_delay: 5
imu:
  i2c_bus: 4
  i2c_addresses: ["0x68", "0x69"]  # Try both addresses due to floating AD0 pin
  sample_rate: 100
  accel_range: 2
  gyro_range: 250
sim:
  port: "/dev/ttyUSB2"
  baudrate: 115200
  ussd_balance_code: "*221#"
  check_interval: 3600
  usage_post_interval: 30  # Interval in seconds to post data usage to backend
  apn: "internet"  # Default APN - replace with your carrier's APN
  dial_command: "ATD*99#"  # Standard dial command for most modems
  ppp_retry_interval: 300  # Try reconnecting PPP every 5 minutes if lost
  interfaces: ["ppp0", "wwan0"]  # Possible LTE interface names
  modem_init_commands:  # Commands to initialize the modem at startup
    - "AT+CFUN=1"  # Set full functionality mode
    - "AT+CGATT=1"  # Attach to network
    - "AT+CREG=1"  # Enable network registration notification
  initialization_retries: 3  # Number of retries for modem initialization
  connection_recovery: true  # Auto-recover when connection is lost
  ppp_setup:
    auto_connect: true  # Automatically try to connect PPP at startup
    connection_script: "/usr/local/bin/lte-connect"  # Created by lte_connection_setup.sh
    chat_script: "/etc/ppp/chat-lte"  # Created by lte_connection_setup.sh
backend:
  url: "https://vehicle-tracking-backend-bwmz.onrender.com"
  endpoint_prefix: "/api"
  detection_endpoint: "/detections"
  sim_data_endpoint: "/sim-data"
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "vehicle_tracker.log"
  offline_file: "offline_data.json"
  interval:
    gps: 1
    imu: 0.05
    camera: 0.2  # Faster camera processing interval (5 frames per second)

network:
  interface: ["ppp0", "wlan0"]  # List of interfaces to track (LTE and WiFi)
  retries: 3
  ping_test_host: "8.8.8.8"  # Google DNS for connectivity tests

api:
  port: 5000

test_server:
  host: "0.0.0.0"  # Listen on all interfaces for LAN access
  port: 8081        # Default test server port
